-- Database Exploration

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- Dimension Exploration

-- Explore all countries our customers come from
SELECT
	DISTINCT country
FROM gold.dim_customers;

-- Explore all categories "The major Divisions"
SELECT
	DISTINCT category, subcategory, product_name
FROM gold.dim_products;

-- Date Exploration

-- Find the date of the first and last order
SELECT
	MIN(order_date) AS First_Order,
	MAX(order_date) AS Last_Order
FROM gold.fact_sales;

-- How many years,months of sales are available
SELECT
	DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS Order_Range_in_years,
	DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) AS Order_Range_in_months
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers;

-- Measures Exploration

-- Find the Total Sales
SELECT
	SUM(sales_amount) AS Total_Sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT
	SUM(quantity) AS Total_Items
FROM gold.fact_sales;

-- Find the average selling price
SELECT
	AVG(price) AS Avg_Selling_Price
FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT
	COUNT(order_number) AS Total_Orders,
	COUNT(DISTINCT order_number) AS Distinct_Orders
FROM gold.fact_sales;

-- Find the Total number of Products
SELECT
	COUNT(DISTINCT product_key) AS Total_Products
FROM gold.dim_products;

-- Find the Total number of customers
SELECT
	COUNT(DISTINCT customer_key) AS Total_Customers
FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT
	COUNT(DISTINCT customer_key) AS Total_Customers
FROM gold.fact_sales;

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;

-- Magnitude Analysis

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC;

-- What is the average costs in each category ?
SELECT
	category,
	AVG(cost) AS Avg_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_Cost DESC;

-- What is the total revenue generated for each category ?
SELECT
	p.category,
	SUM(fs.sales_amount) AS Total_Revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON fs.product_key = p.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC;

-- What is the total revenue generated by each customer ?
SELECT
	c.customer_key,
	SUM(fs.sales_amount) AS Total_Revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales fs
ON c.customer_key = fs.customer_key
GROUP BY c.customer_key
ORDER BY Total_Revenue DESC;

-- What is the distribution of items sold across countries ?
SELECT
	c.country,
	SUM(fs.quantity) AS Total_Quantity
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON fs.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Total_Quantity DESC;

-- Ranking Analysis

-- Which 5 products generate the highest revenue ?
SELECT TOP 5
	p.product_id,
	p.product_name,
	SUM(fs.sales_amount) AS Total_Revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales fs
ON fs.product_key = p.product_key
GROUP BY p.product_id, p.product_name
ORDER BY Total_Revenue DESC;

-- What are the 5 worst-performing products in terms of sales
SELECT TOP 5 WITH TIES
	p.product_id,
	p.product_name,
	SUM(fs.sales_amount) AS Total_Revenue
FROM gold.dim_products p
RIGHT JOIN gold.fact_sales fs
ON fs.product_key = p.product_key
GROUP BY p.product_id, p.product_name
ORDER BY Total_Revenue;

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS Total_Orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_orders;